alias(
    name = "format",
    actual = "//tools/scripts:format",
)

alias(
    name = "compile-commands",
    actual = "@generate_compile_commands",
)

alias(
    name = "buildifier",
    actual = "@com_github_bazelbuild_buildtools//buildifier",
)

alias(
    name = "buildozer",
    actual = "@com_github_bazelbuild_buildtools//buildozer",
)
